openapi: 3.1.0
info:
  version: 1.0.0
  title: Users app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of users app
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations
  - name: Water
    description: Operations about water records.
servers:
  - url: http://localhost:3000
  - url: https://aqua-track-app.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/verify/{token}:
    get:
      $ref: ../swagger/paths/auth/verify/{token}.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    $ref: ../swagger/paths/auth/refresh.yaml
  /auth/requestEmailVerification:
    post:
      $ref: ../swagger/paths/auth/requestEmailVerification.yaml
  /water:
    get:
      $ref: ../swagger/paths/water/get.yaml
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /user/usersCount:
    get:
      $ref: ../swagger/paths/user/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
