openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of users app
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations
  - name: Water
    description: |
      The AquaTrack API allows users to log their daily water intake, edit or delete records, and track their progress towards a daily hydration goal. Users can view their current da's water consumption and analyze their intake over the month.

      Features
      - Log water intake: Users can add a record specifying the amount of water consumed and the time of consumption.
      - Edit entries: Users can update a previously logged water intake.
      - Delete entries: Users can remove a water consumption record.
      - Track daily progress: Users can view their total water consumption for the current day or other day and check if they have met their daily goal.
      - View monthly data: Users can see their water intake records for the entire month, helping them analyze hydration trends.
servers:
  - url: https://aqua-track-app.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/verify/{token}:
    get:
      $ref: ../swagger/paths/auth/verify/{token}.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    $ref: ../swagger/paths/auth/refresh.yaml
  /auth/requestEmailVerification:
    post:
      $ref: ../swagger/paths/auth/requestEmailVerification.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/today:
    get:
      $ref: ../swagger/paths/water/today.yaml
  /water/month:
    get:
      $ref: ../swagger/paths/water/month.yaml
  /user/usersCount:
    get:
      $ref: ../swagger/paths/user/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
